# Generated by Django 3.1.3 on 2020-11-21 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_Image',
            field=models.ImageField(blank=True, null=True, upload_to='image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
