# Generated by Django 3.1.3 on 2020-11-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rank_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='book',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
