# Generated by Django 3.1.3 on 2020-12-07 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_useraccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='dateOfBirth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='mailingAllow',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
    ]
